[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner= """
qemu-system-arm \
-cpu cortex-m3 \
-machine lm3s6965evb \
-semihosting-config enable=on,target=native \
-kernel
"""
# add -nographic flag for redirecting serialoutput to your terminal if nothing is seen
# I removed it for closing qemu with ctrl+c

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]
